### ISSUE TITLE
CSS bug with Bootstrap

### ISSUE THREAD

**Issue by Misiu** [DataTables/KeyTable#22]
Open http://datatables.net/extensions/keytable/examples/styling/bootstrap.html and select third column in first row (Tokyo).
You should see something like this:
![snap 2015-08-25 at 12 52 24](https://cloud.githubusercontent.com/assets/1741838/9466675/e39244dc-4b36-11e5-8512-a6de4a369258.png)
(notice header border over cell selection border)
when it should look like this:
![snap 2015-08-25 at 12 52 34](https://cloud.githubusercontent.com/assets/1741838/9466692/fc904c90-4b36-11e5-92c9-26c8eadb5308.png)

As You can see I've unchecked below CSS:

```
table.table-bordered.dataTable {
    border-collapse: separate !important;
}
```

I'm not sure it this change won't affect other extensions, I checked FixedHeader and without that CSS it look better (in my opinion)
Could You please look at this in Your free time?
Thank You.

**Comment by DataTables** [comment]
Thanks for the bug report. Unfortunately using `border-collapse: collapse`, which Bootstrap does by default, makes the column width calculations virtually impossible when scrolling is active in the DataTable.

I feel that this is really a Chrome rendering bug, since the outline shouldn't be have the border displayed on top of it. But that would need confirmation from the Chrome folks. I'll open a bug when I get a chance to get feedback from them.

**Comment by Misiu** [comment]
Sorry I didn't mentioned that before, but I checked that in Chrome 44 and IE11.

**Comment by DataTables** [comment]
Maybe not Come specific then :-(. If you aren't using scrolling you can safely remove that code. If you want to use scrolling, it is needed (particularly in Firefox).

**Comment by Misiu** [comment]
Allan do You mean scroller plugin? I tried it and after removing that CSS rule it worked fine.

**Comment by DataTables** [comment]
No - the `scrollX` or `scrollY` options in DataTables (although Scroller does require `scrollY`). The results are unpredictable - I've never been able to get `collapse` to work reliably with column widths. You take the width of each column, sum them up and get something that is not the same as the table width!

**Comment by DusanSenior** [comment]
The issue can be probably fixed by z-index property added to dataTables.bootstrap.css like:

table.dataTable thead .sorting, table.dataTable thead .sorting_asc, table.dataTable thead .sorting_desc, table.dataTable thead .sorting_asc_disabled, table.dataTable thead .sorting_desc_disabled {
    cursor: pointer;
    position: relative;
    **z-index: -999;**
}
and maybe somewhere else.
Is it acceptable solution?
Dusan

**Comment by DataTables** [comment]
Not sure about the idea of using z-index to address this as it might cause other layout issues in modals etc. But thanks for posting the suggestion - others might find this workaround useful.

**Comment by Misiu** [comment]
@DusanSenior I've tried Your solution on [KeyTable example page](http://datatables.net/extensions/keytable/examples/styling/bootstrap.html), but after z-index header disappeared (tried -1 and -999):
![snap 2016-02-03 at 16 45 42](https://cloud.githubusercontent.com/assets/1741838/12787412/9c682304-ca95-11e5-9c08-106f71cef2dd.png)

**Comment by DusanSenior** [comment]
Strange, I have used Chrome, it works fine, but it doesn't work in IE, although header is visible but completely not orderable. I agree, it is not good idea. I also need to solve it, I will find ...

**Comment by DusanSenior** [comment]
There is outline-offset property allowing move box inside of the td element, but it is not supported by IE and Edge. So I have decided use background color instead of outline 
file keyTable.bootstrap.css:

table.dataTable th.focus,
table.dataTable td.focus {
  background-color: rgba(51, 122, 183, 0.22)
}

**Comment by DataTables** [comment]
It seems that Edge does [now support outline-offset](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/cssoutlineoffset/), however, that isn't really enough. What I've done is to switch KeyTable to use `box-shadow` (inset) as that is more consistently supported.
